Move `py-unused-deps` check out of `pre-commit`
Because `pre-commit` looks to install tools into an isolated Python
environment, and there's no easy way to install the current package into
that environment. The result is, even with the current package installed
we see errors:

    Error: Could not find metadata for distribution `gha-enforce-sha` is it installed?